name: respy-tut
channels:
  - opensourceeconomics
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  - anaconda-client
  - chaospy
  - jupyterlab
  - line_profiler
  - matplotlib
  - pandas>=0.24
  - pdbpp
  - pre-commit
  - pytest
  - respy>=2.0.0
  - restructuredtext_lint
  - scipy
  - seaborn
